# Generated by Django 4.0.3 on 2026-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tax_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('SSLCommerz', 'SSLCommerz')], max_length=100),
        ),
    ]
